default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.28.2'
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/executablebooks/mdformat
    rev: '0.7.17'
    hooks:
      - id: mdformat

  - repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
      - id: black
        args: ["src", "tests"]

  - repo: https://github.com/timothycrosley/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        args: ["src", "tests"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.6'
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix", "src", "tests" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
      - id: mypy
        args: ["src", "tests"]
        pass_filenames: false
